### ISSUE TITLE
Error: Request timed out

### ISSUE THREAD

**Issue by PatrickHeneise** [mbroadst/amqp10-rpc#1]
I'm trying to put an example together based on the tests in this repo, everything is in Docker containers, I'm using `webcenter/activemq:latest` to run the MQ.

Any idea why I'm getting a timeout here? The call to remote function works, just not the return.

#### client.js
```
const config = require('./config')
const amqp = require('amqp10')
const rpc = require('amqp10-rpc')
amqp.use(rpc())

const client = new amqp.Client()

function request (id) {
  console.log('request')

  client.connect(config.activemq.uri)
    .then(conn => client.createRpcClient('rpc.requests'))
    .then(conn => conn.call('testCall', id))
    .then(result => {
      console.log('result')
      console.log(result)
    })
    .catch(e => {
      console.log('client error')
      console.log(e)
    })
}
```

#### service.js
```
const config = require('./config')
const amqp = require('amqp10')
const rpc = require('amqp10-rpc')
amqp.use(rpc())

const client = new amqp.Client()

client.connect(config.activemq.uri)
  .then(server => client.createRpcServer('rpc.requests'))
  .then(server => server.bind('testCall', function (id) {
    console.log(`testCall(${id})`)
    return id
  }))
  .catch(e => {
    console.log('service error')
    console.log(e)
  })
```

#### result
```
client error
{ AmqpRpcRequestTimeoutError: Request timed out
    at Timeout._onTimeout (/usr/app/node_modules/amqp10-rpc/lib/rpc-client.js:135:43)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
  name: 'AmqpRpcRequestTimeoutError',
  message: 'Request timed out' }
```

**Comment by PatrickHeneise** [comment]
`make test` doesn't seem to work either, except `should support redirecting responses to predefined address`, is it possible the `responseAddress` isn't working properly?
